# Generated by Django 3.2.8 on 2021-11-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation_list',
            old_name='blood_group',
            new_name='chariti',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='blood_group',
            new_name='chariti',
        ),
        migrations.RenameField(
            model_name='requestfund',
            old_name='blood_group',
            new_name='chariti',
        ),
    ]
